// valence — Valence protocol reference implementation (valence/1).
// Umbrella header. Spec: spec/SPEC.md ; registry: registry.yaml.
// Zero dependencies, hardware-free, no heap in steady state, no threads —
// callers drive update(). See lib/valence/library.json.
#pragma once

#include "valence/generated/registry_constants.hpp"
#include "valence/core/result.hpp"
#include "valence/core/clock.hpp"
#include "valence/core/rng.hpp"
#include "valence/core/crypto.hpp"
#include "valence/util/bounded_string.hpp"
#include "valence/util/byte_io.hpp"
#include "valence/util/serial_arithmetic.hpp"
#include "valence/wire/frame_header.hpp"
#include "valence/wire/crc32.hpp"
#include "valence/wire/estop_frame.hpp"
#include "valence/wire/serial_cobs.hpp"
#include "valence/wire/cbor/cbor_writer.hpp"
#include "valence/wire/cbor/cbor_reader.hpp"
#include "valence/wire/messages/hello.hpp"
#include "valence/wire/messages/welcome.hpp"
#include "valence/channel/catalog.hpp"
#include "valence/channel/state_apply.hpp"
#include "valence/channel/safety_events_channel.hpp"
#include "valence/channel/trust_channels.hpp"
#include "valence/wire/sha256.hpp"
#include "valence/wire/catalog_codec.hpp"
#include "valence/wire/catalog_etag.hpp"
#include "valence/wire/blob_chunks.hpp"
#include "valence/wire/stream_bundle.hpp"
#include "valence/wire/packed/layout_codec.hpp"
#include "valence/wire/raw/ping_pong.hpp"
#include "valence/wire/raw/catalog_ready.hpp"
#include "valence/wire/raw/clock_frame.hpp"
#include "valence/wire/raw/probe.hpp"
#include "valence/wire/raw/ackmask.hpp"
#include "valence/wire/raw/beacon.hpp"
#include "valence/wire/messages/blob_req.hpp"
#include "valence/wire/messages/subscribe.hpp"
#include "valence/wire/messages/publish.hpp"
#include "valence/wire/messages/grant.hpp"
#include "valence/wire/messages/intent.hpp"
#include "valence/wire/messages/echo.hpp"
#include "valence/wire/messages/event.hpp"
#include "valence/wire/messages/nack.hpp"
#include "valence/wire/messages/goodbye.hpp"
#include "valence/wire/messages/pair.hpp"
#include "valence/wire/messages/trust_submap.hpp"
#include "valence/wire/messages/auth.hpp"
#include "valence/wire/messages/probe_report.hpp"
#include "valence/session/static_profile.hpp"
#include "valence/wire/frame_buffer.hpp"
#include "valence/wire/fragmentation.hpp"
#include "valence/transport/transport.hpp"
#include "valence/transport/inprocess_binding.hpp"
#include "valence/channel/intent_registry.hpp"
#include "valence/channel/subscription.hpp"
#include "valence/channel/event_channel.hpp"
#include "valence/channel/retained_store.hpp"
#include "valence/session/session.hpp"
#include "valence/session/safety.hpp"
#include "valence/session/pairing.hpp"
#include "valence/session/shedding.hpp"
#include "valence/hub/hub.hpp"
#include "valence/client/client.hpp"
// M5: deadman policy dispatch, takeover, shedding, pairing, probe — done.
