#!/usr/bin/env python3
"""rfc_queue.py -- the RFC queue lives on the Valence board; spec/RFC-QUEUE.md is its generated view.

Operator ruling 2026-10-05: RFCs are beads (type `rfc`, id `rfc-NNN` = the RFC number,
title = the RFC title, description = the entry body verbatim, markdown). The markdown
file is regenerated from the board and committed with every change; it is read by
humans and never hand-edited (spec-editing.md "Queue process").

  python tools/rfc_queue.py export        write spec/RFC-QUEUE.md from the board
  python tools/rfc_queue.py check         exit 1 when the file differs from a fresh export
  python tools/rfc_queue.py import        one-time: create the rfc-NNN beads from the
                                          current file and write spec/rfc/preamble.md
                                          (idempotent: existing ids are skipped)
  python tools/rfc_queue.py new NNN "title" [--body-file f]
                                          create a draft entry on the board (then export)

Constraints:
- The body's own "- **Status:** ..." line is the record of an RFC's state; the bead's
  status and `status:*` label mirror it (set by import, maintained by `bd update`).
- Every entry carries an explicit anchor `<a id="rfc-NNN"></a>`; links use `#rfc-NNN`.
- The preamble (header, dispositions, historical indexes) is spec/rfc/preamble.md,
  hand-maintained prose that is not an RFC.
- Shells out to `bd` only; never touches the Dolt files.
"""
import json
import os
import re
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
QUEUE = os.path.join(ROOT, 'spec', 'RFC-QUEUE.md')
PREAMBLE = os.path.join(ROOT, 'spec', 'rfc', 'preamble.md')
HEADING = re.compile(r'^## RFC-(\d{3})\s+(?:—|--|–)\s+(.+?)\s*$')
ANCHOR_LINK = re.compile(r'\(#rfc-(\d{3})-[^)]*\)')
STATUS_LINE = re.compile(r'^- \*\*Status:\*\*\s*(.*)$', re.M)
GENERATED = '<!-- GENERATED by tools/rfc_queue.py from the Valence board (bd, type rfc). Edit the bead, run export, commit both. Never hand-edit. -->'


def bd(*args, check=True, inp=None):
    r = subprocess.run(['bd', *args], cwd=ROOT, capture_output=True, text=True, encoding='utf-8', input=inp)
    if check and r.returncode != 0:
        sys.exit('bd %s failed: %s' % (' '.join(args), r.stderr.strip() or r.stdout.strip()))
    return r.stdout


def read(path):
    with open(path, encoding='utf-8', newline='') as f:
        return f.read()


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8', newline='') as f:
        f.write(text)


def status_word(body):
    """The first word of the entry's own Status line, uppercased: DRAFT, ACCEPTED, LANDED, PARTIALLY, REJECTED, WITHDRAWN, DEFERRED."""
    m = STATUS_LINE.search(body)
    if not m:
        return 'UNKNOWN'
    w = re.sub(r'[*_`]', '', m.group(1)).strip().split()
    return (w[0] if w else 'UNKNOWN').upper().rstrip(',.:;')


def label_for(word):
    return {
        'DRAFT': 'status:draft', 'ACCEPTED': 'status:accepted', 'LANDED': 'status:landed',
        'PARTIALLY': 'status:partial', 'REJECTED': 'status:rejected', 'WITHDRAWN': 'status:withdrawn',
        'DEFERRED': 'status:deferred',
    }.get(word, 'status:unknown')


def bead_status_for(word):
    if word in ('LANDED', 'REJECTED', 'WITHDRAWN'):
        return 'closed'
    if word == 'DEFERRED':
        return 'deferred'
    return 'open'


# ---- parsing the current file (import) ---------------------------------------

def split_file(text):
    """Returns (preamble_parts, entries). An entry is (num, title, body); the body is
    everything from the line after the heading to the next '## ' heading. Non-RFC
    '## ' sections are preamble parts, in file order."""
    nl = '\r\n' if '\r\n' in text else '\n'
    lines = text.split(nl)
    cuts = [i for i, l in enumerate(lines) if l.startswith('## ')]
    cuts.append(len(lines))
    preamble = [nl.join(lines[:cuts[0]]).rstrip('\r\n')]
    entries = []
    for a, b in zip(cuts, cuts[1:]):
        head = lines[a]
        block = lines[a + 1:b]
        while block and not block[-1].strip():
            block.pop()
        if block and block[-1].strip() == '---':
            block.pop()
            while block and not block[-1].strip():
                block.pop()
        m = HEADING.match(head)
        if m:
            entries.append((int(m.group(1)), m.group(2), nl.join(block)))
        else:
            preamble.append(head + nl + nl.join(block))
    return preamble, entries, nl


def rewrite_anchors(text):
    return ANCHOR_LINK.sub(lambda m: '(#rfc-%s)' % m.group(1), text)


def cmd_import():
    text = read(QUEUE)
    preamble, entries, nl = split_file(text)
    existing = {i['id'] for i in json.loads(bd('list', '--all', '--json', '--flat') or '[]')}
    write(PREAMBLE, rewrite_anchors((nl + nl).join(preamble)).rstrip('\r\n') + nl)
    print('preamble: %d parts -> %s' % (len(preamble), os.path.relpath(PREAMBLE, ROOT)))
    made = skipped = 0
    for num, title, body in entries:
        bid = 'rfc-%03d' % num
        if bid in existing:
            skipped += 1
            continue
        body = rewrite_anchors(body)
        word = status_word(body)
        with tempfile.NamedTemporaryFile('w', encoding='utf-8', newline='', suffix='.md', delete=False) as f:
            f.write(body)
            tmp = f.name
        try:
            bd('create', title, '--id', bid, '-t', 'rfc', '--body-file', tmp, '-l', label_for(word), '--no-inherit-labels')
        finally:
            os.unlink(tmp)
        st = bead_status_for(word)
        if st == 'closed':
            bd('close', bid, '--reason', 'Imported 2026-10-05 with its own Status line: %s' % word.title())
        elif st == 'deferred':
            bd('update', bid, '--status', 'deferred')
        made += 1
        print('  %s %-9s %s' % (bid, word, title[:70]))
    print('created %d, skipped %d existing' % (made, skipped))


# ---- rendering (export / check) ------------------------------------------------

def load_board():
    rows = []
    for line in bd('export').splitlines():
        if not line.strip():
            continue
        rec = json.loads(line)
        if rec.get('_type', 'issue') != 'issue' or rec.get('issue_type') != 'rfc':
            continue
        m = re.fullmatch(r'rfc-(\d{3})', rec['id'])
        if not m:
            continue
        rows.append((int(m.group(1)), rec))
    rows.sort(key=lambda r: r[0])
    return rows


def render():
    pre = read(PREAMBLE) if os.path.exists(PREAMBLE) else ''
    nl = '\r\n' if '\r\n' in pre else '\n'
    rows = load_board()
    out = [GENERATED, '']
    out.append(pre.rstrip('\r\n'))
    out += ['', '## Index', '', '*Generated from the board: the status is the first word of each entry\'s own Status line.*', '',
            '| RFC | Title | Status | Board |', '|---|---|---|---|']
    for num, rec in rows:
        word = status_word(rec.get('description') or '')
        out.append('| [%03d](#rfc-%03d) | %s | %s | %s |' % (num, num, rec['title'].replace('|', '\\|'), word.title(), rec.get('status', '')))
    out.append('')
    for num, rec in rows:
        out += ['', '<a id="rfc-%03d"></a>' % num, '## RFC-%03d -- %s' % (num, rec['title']), '',
                (rec.get('description') or '').replace('\r\n', '\n').replace('\n', nl).rstrip('\r\n'), '', '---']
    text = nl.join(out).rstrip('\r\n') + nl
    return text.replace('\r\n', nl).replace('\n', nl) if nl == '\r\n' else text


def cmd_export():
    text = render()
    write(QUEUE, text)
    print('wrote %s (%d bytes, %d entries)' % (os.path.relpath(QUEUE, ROOT), len(text.encode('utf-8')), text.count('<a id="rfc-')))


def cmd_check():
    fresh = render()
    current = read(QUEUE) if os.path.exists(QUEUE) else ''
    if fresh.replace('\r\n', '\n') != current.replace('\r\n', '\n'):
        print('rfc-queue-drift: spec/RFC-QUEUE.md differs from the board; run `python tools/rfc_queue.py export`')
        sys.exit(1)
    print('rfc-queue: in sync (%d entries)' % fresh.count('<a id="rfc-'))


def cmd_new(argv):
    if len(argv) < 2:
        sys.exit('usage: rfc_queue.py new NNN "title" [--body-file f]')
    num = int(argv[0])
    title = argv[1]
    body_file = argv[argv.index('--body-file') + 1] if '--body-file' in argv else None
    bid = 'rfc-%03d' % num
    args = ['create', title, '--id', bid, '-t', 'rfc', '-l', 'status:draft', '--no-inherit-labels']
    if body_file:
        args += ['--body-file', body_file]
    else:
        args += ['-d', '- **Status:** DRAFT\n- **Origin.**\n- **Problem.**\n- **Proposal.**\n- **Pros.**\n- **Cons.**\n- **Cost.**\n- **Wire impact.**\n- **Open questions.**']
    bd(*args)
    print('created %s; edit with `bd update %s --body-file <md>`, then export' % (bid, bid))


if __name__ == '__main__':
    cmd = sys.argv[1] if len(sys.argv) > 1 else 'check'
    {'import': lambda: cmd_import(), 'export': cmd_export, 'check': cmd_check, 'new': lambda: cmd_new(sys.argv[2:])}.get(cmd, lambda: sys.exit(__doc__))()
